name: Node CI

on: [push]

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.11.x]

    steps:
      - uses: actions/checkout@v1
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up MySQL 5.7
        uses: mirromutth/mysql-action@master
        with:
          mysql version: 5.7
          mysql database: clean_architecture_typescript_test
          mysql root password: root
      - name: npm install, build, and test
        run: |
          npm install
          npm test
        env:
          CI: true
          NODE_ENV: "test"
          GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
